services:
  backend:
    build: ./backend
    container_name: brains-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    container_name: brains-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
